services:
  - type: web
    name: teacher-eval-api
    environment: php
    plan: free
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:8080
    envVars:
      - key: DB_HOST
        scope: build,runtime
        value: mongodb+srv://teacher_eval_user:Alhamer1@cluster0.xveslur.mongodb.net/teacher_eval?retryWrites=true&w=majority
      - key: DB_NAME
        scope: build,runtime
        value: teacher_eval
      - key: APP_ENV
        scope: build,runtime
        value: production
      - key: APP_DEBUG
        scope: build,runtime
        value: "false"
      - key: JWT_SECRET
        scope: build,runtime
        value: teacher_eval_secret_key_2024_april_secure
      - key: APP_URL
        scope: runtime
        value: https://teacher-eval-api.onrender.com
